"""Lazy MCP warm pool with per-server idle TTL.

Bucket-1 in-process MCP servers (hikari_*) are always attached.
Bucket-3 external MCPs (google_workspace, notion, github, playwright, etc.)
spawn ON FIRST acquire and shut down after idle TTL.

The pool is process-local (one per Hikari runtime). Subprocess lifecycle
matches the SDK's MCP child management — we do not directly spawn; we
only track WHICH MCPs should be attached to the next SDK options build.

Direct MCP call surface (Sprint 7B):
  MANAGER.call(server_name, tool_name, arguments) — spawns a stdio MCP
  subprocess per server, caches one ClientSession per server, reuses
  across calls. Reads server config from .mcp.json.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from contextlib import AsyncExitStack
from pathlib import Path
from typing import Any

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from mcp.types import CallToolResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Path to the authoritative MCP server config.
# Generated by scripts/regen_mcp_json.py from config/tools.yaml.
# ---------------------------------------------------------------------------
_MCP_JSON = Path(__file__).parent.parent / ".mcp.json"


class McpCallError(Exception):
    """Raised when a direct MCP tool call fails (server error, tool error, etc.)."""

    def __init__(self, server: str, tool: str, message: str) -> None:
        self.server = server
        self.tool = tool
        self.message = message
        super().__init__(f"MCP error [{server}/{tool}]: {message}")


def _load_mcp_json() -> dict[str, Any]:
    if not _MCP_JSON.exists():
        raise FileNotFoundError(
            f".mcp.json not found at {_MCP_JSON}. "
            "Run `uv run python scripts/regen_mcp_json.py` first."
        )
    with _MCP_JSON.open() as fh:
        return json.load(fh)


def _expand_env(value: str) -> str:
    """Expand ${VAR} references in a string using the current environment."""
    import re

    def _replace(m: re.Match) -> str:
        var = m.group(1)
        return os.environ.get(var, "")

    return re.sub(r"\$\{([^}]+)\}", _replace, value)


def _build_server_params(server_name: str) -> StdioServerParameters:
    """Read .mcp.json and return StdioServerParameters for `server_name`."""
    data = _load_mcp_json()
    servers = data.get("mcpServers", {})
    if server_name not in servers:
        raise KeyError(
            f"Server '{server_name}' not found in .mcp.json. "
            f"Available: {sorted(servers)}"
        )
    spec = servers[server_name]
    command: str = spec["command"]
    args: list[str] = [str(a) for a in spec.get("args", [])]
    raw_env: dict[str, str] = spec.get("env", {}) or {}
    env: dict[str, str] = {k: _expand_env(v) for k, v in raw_env.items()}
    return StdioServerParameters(command=command, args=args, env=env)


def _result_to_dict(result: CallToolResult) -> dict[str, Any]:
    """Normalize a CallToolResult into a plain dict.

    Priority:
      1. structuredContent  — already a dict, return as-is.
      2. content[0].text    — TextContent: return {"text": ...}
      3. content[0].data    — ImageContent/AudioContent: return {"data": ..., "mimeType": ...}
      4. fallback            — serialize all content items.
    """
    if result.structuredContent is not None:
        return dict(result.structuredContent)

    if not result.content:
        return {}

    first = result.content[0]
    # TextContent
    if hasattr(first, "text"):
        return {"text": first.text}
    # ImageContent / AudioContent
    if hasattr(first, "data"):
        out: dict[str, Any] = {"data": first.data}
        if hasattr(first, "mimeType"):
            out["mimeType"] = first.mimeType
        return out
    # EmbeddedResource / ResourceLink / unknown — serialize all
    return {"content": [c.model_dump() for c in result.content]}


class _SessionHandle:
    """Cached stdio MCP session for one server."""

    def __init__(self, server_name: str) -> None:
        self.server_name = server_name
        self.session: ClientSession | None = None
        self._exit_stack: AsyncExitStack | None = None
        self._lock = asyncio.Lock()  # serializes spawn; concurrent call_tool is fine


async def _spawn_session(server_name: str) -> tuple[ClientSession, AsyncExitStack]:
    """Spawn an MCP stdio subprocess for `server_name`.

    Returns (session, exit_stack). The caller owns the stack and must call
    `await exit_stack.aclose()` on shutdown.
    """
    params = _build_server_params(server_name)
    stack = AsyncExitStack()
    try:
        read, write = await stack.enter_async_context(stdio_client(params))
        session: ClientSession = await stack.enter_async_context(
            ClientSession(read, write)
        )
        await session.initialize()
        logger.info("mcp_manager: spawned session for %s", server_name)
        return session, stack
    except Exception:
        await stack.aclose()
        raise

_DEFAULT_TTL_S = 60


class McpManager:
    def __init__(self) -> None:
        # server_name -> last_acquired_epoch
        self._last_acquired: dict[str, float] = {}
        self._lock = asyncio.Lock()
        # per-server TTL config (seconds)
        self._ttl: dict[str, int] = {}
        # Direct-call session cache (server_name -> _SessionHandle)
        self._sessions: dict[str, _SessionHandle] = {}

    def configure_ttls(self, ttls: dict[str, int]) -> None:
        self._ttl = dict(ttls)

    def _ttl_for(self, server_name: str) -> int:
        return int(self._ttl.get(server_name, _DEFAULT_TTL_S))

    async def acquire(self, server_name: str) -> None:
        """Mark a server as actively in use. Idempotent. Returns immediately."""
        async with self._lock:
            self._last_acquired[server_name] = time.time()
            logger.debug("mcp_manager: acquired %s", server_name)

    def is_warm(self, server_name: str) -> bool:
        last = self._last_acquired.get(server_name)
        if last is None:
            return False
        return (time.time() - last) < self._ttl_for(server_name)

    def warm_servers(self) -> set[str]:
        """Return the set of currently-warm server names."""
        now = time.time()
        return {
            name for name, last in self._last_acquired.items()
            if (now - last) < self._ttl_for(name)
        }

    async def evict_stale(self) -> list[str]:
        """Remove stale entries. Returns names of evicted servers."""
        now = time.time()
        evicted = []
        async with self._lock:
            for name in list(self._last_acquired.keys()):
                last = self._last_acquired[name]
                if (now - last) >= self._ttl_for(name):
                    del self._last_acquired[name]
                    evicted.append(name)
        if evicted:
            logger.info("mcp_manager: evicted stale %s", evicted)
        return evicted

    # ------------------------------------------------------------------
    # Direct MCP call surface (Sprint 7B)
    # ------------------------------------------------------------------

    async def call(
        self,
        server_name: str,
        tool_name: str,
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        """Invoke an MCP tool directly, bypassing the LLM.

        Caches one ClientSession per server. On first call for a server, spawns
        the stdio subprocess and runs initialize(). Subsequent calls reuse the
        live session. Bumps TTL via acquire() after each successful call.

        Raises McpCallError if the tool returns isError=True or if the
        underlying call raises an exception.
        """
        handle = self._sessions.setdefault(server_name, _SessionHandle(server_name))
        async with handle._lock:
            if handle.session is None:
                handle.session, handle._exit_stack = await _spawn_session(server_name)
            session = handle.session
            assert session is not None

        try:
            result: CallToolResult = await session.call_tool(
                tool_name, arguments=arguments
            )
        except Exception as exc:
            raise McpCallError(server_name, tool_name, str(exc)) from exc

        if result.isError:
            # Extract the error message from content if possible
            msg = "tool reported isError=True"
            if result.content:
                first = result.content[0]
                if hasattr(first, "text"):
                    msg = first.text
            raise McpCallError(server_name, tool_name, msg)

        # Bump warm-pool TTL
        await self.acquire(server_name)

        return _result_to_dict(result)

    async def shutdown_sessions(self) -> None:
        """Close all cached direct-call sessions. Call from bot shutdown path.

        Hook location in agents/telegram_bridge.py:
          post_shutdown (line 2401) — add `await MANAGER.shutdown_sessions()`
          after `await _sdk_pool.shutdown()`, before the except block.
        """
        for handle in list(self._sessions.values()):
            if handle._exit_stack is not None:
                try:
                    await handle._exit_stack.aclose()
                    logger.info(
                        "mcp_manager: closed session for %s", handle.server_name
                    )
                except Exception:  # noqa: BLE001
                    logger.exception(
                        "mcp_manager: error closing session for %s",
                        handle.server_name,
                    )
        self._sessions.clear()


MANAGER: McpManager = McpManager()


def configure_from_registry() -> None:
    """Load per-server warm_pool_ttl_sec from config/tools.yaml at boot."""
    try:
        from tools._tools_yaml import load_registry
        reg = load_registry()
        mcp_servers = reg.mcp_servers()
        ttls: dict[str, int] = {}
        for name, spec in mcp_servers.items():
            ttls[str(name)] = int(spec.warm_pool_ttl_sec)
        MANAGER.configure_ttls(ttls)
        logger.info("mcp_manager: configured TTLs for %d servers", len(ttls))
    except Exception:
        logger.exception("mcp_manager: failed to configure TTLs from registry")
