"""Lazy MCP warm pool with per-server idle TTL.

Bucket-1 in-process MCP servers (hikari_*) are always attached.
Bucket-3 external MCPs (google_workspace, notion, github, playwright, etc.)
spawn ON FIRST acquire and shut down after idle TTL.

The pool is process-local (one per Hikari runtime). Subprocess lifecycle
matches the SDK's MCP child management — we do not directly spawn; we
only track WHICH MCPs should be attached to the next SDK options build.

Direct MCP call surface (Sprint 7B):
  MANAGER.call(server_name, tool_name, arguments) — spawns a stdio MCP
  subprocess per server, caches one ClientSession per server, reuses
  across calls. Reads server config from .mcp.json.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from contextlib import AsyncExitStack
from pathlib import Path
from typing import Any

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from mcp.types import CallToolResult

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Path to the authoritative MCP server config.
# Generated by scripts/regen_mcp_json.py from config/tools.yaml.
# ---------------------------------------------------------------------------
_MCP_JSON = Path(__file__).parent.parent / ".mcp.json"


class McpCallError(Exception):
    """Raised when a direct MCP tool call fails (server error, tool error, etc.)."""

    def __init__(self, server: str, tool: str, message: str) -> None:
        self.server = server
        self.tool = tool
        self.message = message
        super().__init__(f"MCP error [{server}/{tool}]: {message}")


def _load_mcp_json() -> dict[str, Any]:
    if not _MCP_JSON.exists():
        raise FileNotFoundError(
            f".mcp.json not found at {_MCP_JSON}. "
            "Run `uv run python scripts/regen_mcp_json.py` first."
        )
    with _MCP_JSON.open() as fh:
        return json.load(fh)


def _expand_env(value: str) -> str:
    """Expand ${VAR} references in a string using the current environment."""
    import re

    def _replace(m: re.Match) -> str:
        var = m.group(1)
        return os.environ.get(var, "")

    return re.sub(r"\$\{([^}]+)\}", _replace, value)


def _build_server_params(server_name: str) -> StdioServerParameters:
    """Read .mcp.json and return StdioServerParameters for `server_name`."""
    data = _load_mcp_json()
    servers = data.get("mcpServers", {})
    if server_name not in servers:
        raise KeyError(
            f"Server '{server_name}' not found in .mcp.json. "
            f"Available: {sorted(servers)}"
        )
    spec = servers[server_name]
    command: str = spec["command"]
    args: list[str] = [str(a) for a in spec.get("args", [])]
    raw_env: dict[str, str] = spec.get("env", {}) or {}
    env: dict[str, str] = {k: _expand_env(v) for k, v in raw_env.items()}
    return StdioServerParameters(command=command, args=args, env=env)


def _result_to_dict(result: CallToolResult) -> dict[str, Any]:
    """Normalize a CallToolResult into a plain dict.

    Priority:
      1. structuredContent  — already a dict, return as-is.
      2. content[0].text    — TextContent: return {"text": ...}
      3. content[0].data    — ImageContent/AudioContent: return {"data": ..., "mimeType": ...}
      4. fallback            — serialize all content items.
    """
    if result.structuredContent is not None:
        return dict(result.structuredContent)

    if not result.content:
        return {}

    first = result.content[0]
    # TextContent
    if hasattr(first, "text"):
        return {"text": first.text}
    # ImageContent / AudioContent
    if hasattr(first, "data"):
        out: dict[str, Any] = {"data": first.data}
        if hasattr(first, "mimeType"):
            out["mimeType"] = first.mimeType
        return out
    # EmbeddedResource / ResourceLink / unknown — serialize all
    return {"content": [c.model_dump() for c in result.content]}


class _CallCmd:
    """A request to invoke one tool, submitted to a server's supervisor task."""

    __slots__ = ("tool_name", "arguments", "timeout", "future")

    def __init__(
        self,
        tool_name: str,
        arguments: dict[str, Any],
        timeout: float,
        future: asyncio.Future[CallToolResult],
    ) -> None:
        self.tool_name = tool_name
        self.arguments = arguments
        self.timeout = timeout
        self.future = future


class _CloseCmd:
    """A request to tear the session down and stop the supervisor task."""

    __slots__ = ("future",)

    def __init__(self, future: asyncio.Future[None]) -> None:
        self.future = future


class _SessionHandle:
    """Coordinator for one server's stdio MCP session.

    The session's ``AsyncExitStack`` is entered AND exited exclusively by a
    single long-lived supervisor task (``_supervise``). Callers never touch the
    stack directly — they submit ``_CallCmd`` / ``_CloseCmd`` messages onto
    ``queue`` and await a per-request future. This guarantees that the anyio
    task group inside ``stdio_client`` (whose cancel scope is task-bound) is
    only ever unwound in the same task that created it. Closing that stack from
    a foreign task raises "attempted to exit cancel scope in a different task"
    and leaks the child subprocess — the class of bug this design eliminates.

    ``session`` / ``_exit_stack`` are owned and mutated *only* by the supervisor
    task; callers must treat them as read-only state.
    """

    def __init__(self, server_name: str) -> None:
        self.server_name = server_name
        self.session: ClientSession | None = None
        self._exit_stack: AsyncExitStack | None = None
        self.queue: asyncio.Queue[_CallCmd | _CloseCmd] = asyncio.Queue()
        self._supervisor: asyncio.Task[None] | None = None
        self._start_lock = asyncio.Lock()  # guards supervisor (re)creation only


async def _spawn_session(server_name: str) -> tuple[ClientSession, AsyncExitStack]:
    """Spawn an MCP stdio subprocess for `server_name`.

    Returns (session, exit_stack). The caller owns the stack and must call
    `await exit_stack.aclose()` on shutdown.
    """
    params = _build_server_params(server_name)
    stack = AsyncExitStack()
    try:
        read, write = await stack.enter_async_context(stdio_client(params))
        session: ClientSession = await stack.enter_async_context(
            ClientSession(read, write)
        )
        await session.initialize()
        logger.info("mcp_manager: spawned session for %s", server_name)
        return session, stack
    except Exception:
        await stack.aclose()
        raise


async def _teardown(handle: _SessionHandle) -> None:
    """Close a server's exit stack. MUST run in the supervisor task.

    Nulls ``session`` / ``_exit_stack`` first so a partially-failed close still
    forces a fresh respawn on the next call. Closing the anyio-backed stdio
    stack is what actually terminates the child subprocess (stdin close →
    SIGTERM → SIGKILL, see mcp.client.stdio); a swallowed failure here can mean
    a leaked process, so it is logged at WARNING with the server name rather
    than hidden.
    """
    stack = handle._exit_stack
    handle.session = None
    handle._exit_stack = None
    if stack is None:
        return
    try:
        await stack.aclose()
    except Exception:  # noqa: BLE001
        logger.warning(
            "mcp_manager: error tearing down session for %s; child subprocess "
            "may not have terminated cleanly",
            handle.server_name,
            exc_info=True,
        )


async def _supervise(handle: _SessionHandle) -> None:
    """Own one server's session for its entire lifetime.

    Spawns the stdio subprocess on demand and, crucially, is the ONLY task that
    ever closes it — so the anyio cancel scope inside ``stdio_client`` is always
    unwound in the task that created it. Processes messages serially: a slow or
    hung call blocks that server's queue but can never tear a session down out
    from under a concurrent in-flight call (there is only ever one in flight).
    """
    server_name = handle.server_name
    while True:
        cmd = await handle.queue.get()

        if isinstance(cmd, _CloseCmd):
            await _teardown(handle)
            if not cmd.future.done():
                cmd.future.set_result(None)
            return  # supervisor exits; a later call() respawns a fresh one

        # _CallCmd
        try:
            if handle.session is None:
                handle.session, handle._exit_stack = await _spawn_session(server_name)
            result = await asyncio.wait_for(
                handle.session.call_tool(cmd.tool_name, arguments=cmd.arguments),
                timeout=cmd.timeout,
            )
        except Exception as exc:  # includes TimeoutError from wait_for
            # Session may be wedged — evict it (in THIS task) so the next call
            # respawns a fresh subprocess instead of retrying a dead one.
            await _teardown(handle)
            logger.warning(
                "mcp_manager: evicted session for %s after error: %s",
                server_name, exc,
            )
            if not cmd.future.done():
                cmd.future.set_exception(exc)
        else:
            if not cmd.future.done():
                cmd.future.set_result(result)


_DEFAULT_TTL_S = 60
_DEFAULT_CALL_TIMEOUT_S = 30
# How long shutdown_sessions() waits for a supervisor to drain + close before
# force-cancelling it.
_SHUTDOWN_CLOSE_TIMEOUT_S = 15


def _load_call_timeouts() -> dict[str, int]:
    """Read direct_call_timeout_sec per server from config/tools.yaml.

    Returns a mapping of server_name -> timeout_seconds. Servers that don't
    define the key are not included; callers fall back to _DEFAULT_CALL_TIMEOUT_S.

    Best-effort: returns {} on any parse/IO error so a missing or malformed
    config never prevents the manager from starting.
    """
    import yaml  # pyyaml is already a dep (used by agents/config.py)

    _TOOLS_YAML = Path(__file__).parent.parent / "config" / "tools.yaml"
    try:
        with _TOOLS_YAML.open() as fh:
            data = yaml.safe_load(fh)
        servers = (data or {}).get("mcp_servers") or {}
        out: dict[str, int] = {}
        for name, spec in servers.items():
            if isinstance(spec, dict) and "direct_call_timeout_sec" in spec:
                try:
                    out[str(name)] = int(spec["direct_call_timeout_sec"])
                except (ValueError, TypeError):
                    pass
        return out
    except Exception:
        logger.debug("mcp_manager: could not load call timeouts from tools.yaml", exc_info=True)
        return {}


class McpManager:
    def __init__(self) -> None:
        # server_name -> last_acquired_epoch
        self._last_acquired: dict[str, float] = {}
        self._lock = asyncio.Lock()
        # per-server TTL config (seconds)
        self._ttl: dict[str, int] = {}
        # per-server direct-call timeout (seconds); populated at configure time
        self._call_timeouts: dict[str, int] = {}
        # Direct-call session cache (server_name -> _SessionHandle)
        self._sessions: dict[str, _SessionHandle] = {}

    def configure_ttls(self, ttls: dict[str, int]) -> None:
        self._ttl = dict(ttls)
        # Also reload per-server call timeouts when TTLs are reconfigured —
        # both come from config/tools.yaml so they're updated together.
        self._call_timeouts = _load_call_timeouts()

    def _ttl_for(self, server_name: str) -> int:
        return int(self._ttl.get(server_name, _DEFAULT_TTL_S))

    def _call_timeout_for(self, server_name: str) -> int:
        """Return the per-call asyncio.wait_for timeout (seconds) for this server.

        Source priority:
          1. ``direct_call_timeout_sec`` from config/tools.yaml for this server.
          2. Module-level ``_DEFAULT_CALL_TIMEOUT_S`` (30 s).
        """
        return int(self._call_timeouts.get(server_name, _DEFAULT_CALL_TIMEOUT_S))

    async def acquire(self, server_name: str) -> None:
        """Mark a server as actively in use. Idempotent. Returns immediately."""
        async with self._lock:
            self._last_acquired[server_name] = time.time()
            logger.debug("mcp_manager: acquired %s", server_name)

    def is_warm(self, server_name: str) -> bool:
        last = self._last_acquired.get(server_name)
        if last is None:
            return False
        return (time.time() - last) < self._ttl_for(server_name)

    def warm_servers(self) -> set[str]:
        """Return the set of currently-warm server names."""
        now = time.time()
        return {
            name for name, last in self._last_acquired.items()
            if (now - last) < self._ttl_for(name)
        }

    async def evict_stale(self) -> list[str]:
        """Remove stale entries. Returns names of evicted servers."""
        now = time.time()
        evicted = []
        async with self._lock:
            for name in list(self._last_acquired.keys()):
                last = self._last_acquired[name]
                if (now - last) >= self._ttl_for(name):
                    del self._last_acquired[name]
                    evicted.append(name)
        if evicted:
            logger.info("mcp_manager: evicted stale %s", evicted)
        return evicted

    # ------------------------------------------------------------------
    # Direct MCP call surface (Sprint 7B)
    # ------------------------------------------------------------------

    async def _ensure_supervisor(self, handle: _SessionHandle) -> None:
        """Start the server's supervisor task if it isn't already running.

        A supervisor exits after a ``_CloseCmd`` (or an unexpected crash); this
        transparently (re)spawns one on the next call. The start lock makes
        concurrent callers race-free without serializing the calls themselves —
        actual work is dispatched through the queue, not the lock.
        """
        if handle._supervisor is not None and not handle._supervisor.done():
            return
        async with handle._start_lock:
            if handle._supervisor is not None and not handle._supervisor.done():
                return
            handle._supervisor = asyncio.create_task(
                _supervise(handle), name=f"mcp-supervisor-{handle.server_name}"
            )

    async def call(
        self,
        server_name: str,
        tool_name: str,
        arguments: dict[str, Any],
    ) -> dict[str, Any]:
        """Invoke an MCP tool directly, bypassing the LLM.

        Caches one ClientSession per server. On first call for a server, spawns
        the stdio subprocess and runs initialize(). Subsequent calls reuse the
        live session. Bumps TTL via acquire() after each successful call.

        Raises McpCallError if the tool returns isError=True or if the
        underlying call raises an exception.
        """
        handle = self._sessions.setdefault(server_name, _SessionHandle(server_name))
        await self._ensure_supervisor(handle)

        timeout = self._call_timeout_for(server_name)
        future: asyncio.Future[CallToolResult] = asyncio.get_running_loop().create_future()
        # Hand the work to the server's supervisor task: it — and only it —
        # spawns, calls, and (on error/timeout) tears down the session, so the
        # anyio stdio stack is never closed from a foreign task.
        await handle.queue.put(_CallCmd(tool_name, arguments, timeout, future))

        try:
            result: CallToolResult = await future
        except Exception as exc:
            raise McpCallError(server_name, tool_name, str(exc)) from exc

        if result.isError:
            # Extract the error message from content if possible
            msg = "tool reported isError=True"
            if result.content:
                first = result.content[0]
                if hasattr(first, "text"):
                    msg = first.text
            raise McpCallError(server_name, tool_name, msg)

        # Bump warm-pool TTL
        await self.acquire(server_name)

        return _result_to_dict(result)

    async def shutdown_sessions(self) -> None:
        """Close all cached direct-call sessions. Call from bot shutdown path.

        Each session is torn down by its own supervisor task (via a _CloseCmd),
        so the anyio stdio stack is unwound in the task that entered it — never
        from this shutdown caller's task. A supervisor that won't drain within
        _SHUTDOWN_CLOSE_TIMEOUT_S is force-cancelled as a last resort.

        Hook location in agents/telegram_bridge.py:
          post_shutdown (line 2401) — add `await MANAGER.shutdown_sessions()`
          after `await _sdk_pool.shutdown()`, before the except block.
        """
        loop = asyncio.get_running_loop()
        for handle in list(self._sessions.values()):
            sup = handle._supervisor
            if sup is None or sup.done():
                # No live owner. We must NOT aclose the stack from here (foreign
                # task) — that is exactly the bug this design avoids. If a stack
                # somehow lingers, warn rather than leak silently.
                if handle._exit_stack is not None:
                    logger.warning(
                        "mcp_manager: %s has a live exit_stack but no running "
                        "supervisor; child subprocess may leak",
                        handle.server_name,
                    )
                continue
            close_future: asyncio.Future[None] = loop.create_future()
            await handle.queue.put(_CloseCmd(close_future))
            try:
                await asyncio.wait_for(sup, timeout=_SHUTDOWN_CLOSE_TIMEOUT_S)
                logger.info(
                    "mcp_manager: closed session for %s", handle.server_name
                )
            except Exception:  # noqa: BLE001  (includes TimeoutError)
                logger.warning(
                    "mcp_manager: supervisor for %s did not shut down cleanly; "
                    "cancelling it",
                    handle.server_name, exc_info=True,
                )
                sup.cancel()
                try:
                    await sup
                except (asyncio.CancelledError, Exception):  # noqa: BLE001
                    pass
        self._sessions.clear()


MANAGER: McpManager = McpManager()


def configure_from_registry() -> None:
    """Load per-server warm_pool_ttl_sec from config/tools.yaml at boot."""
    try:
        from tools._tools_yaml import load_registry
        reg = load_registry()
        mcp_servers = reg.mcp_servers()
        ttls: dict[str, int] = {}
        for name, spec in mcp_servers.items():
            ttls[str(name)] = int(spec.warm_pool_ttl_sec)
        MANAGER.configure_ttls(ttls)
        logger.info("mcp_manager: configured TTLs for %d servers", len(ttls))
    except Exception:
        logger.exception("mcp_manager: failed to configure TTLs from registry")
